"""add chunk embeddings

Revision ID: a0f3cc91af42
Revises: 87568fb188c8
Create Date: 2026-09-30 08:26:45.013515

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a0f3cc91af42'
down_revision: Union[str, Sequence[str], None] = '87568fb188c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
